services:
  app:
    build: ./
    ports:
      - 5173:5173
    volumes:
      - "./:/app"
      - "app-nodemodules:/app/node_modules"
    command: "npm run dev -- --host"

volumes:
  app-nodemodules: