image: node:18

pipelines:
  pull-requests:
    "**":
      - step:
          name: Frontend Linting
          script:
            - cd frontend/
            - npm install
            - npm run lint
            - npm test
          caches:
            - node
      - step:
          name: Backend linting
          script:
            - cd backend/
            - npm install
            - npm run lint
            - npm test
          caches:
            - node
