services:
  middleware:
    build:
      context: ./
      dockerfile: Dockerfile.local
    ports:
      - 3000:3000
      - 3443:3443
      - 9229:9229
    volumes:
      - .:/app
      - middleware-nodemodules:/app/node_modules
    links:
      - db
    env_file:
      - .env
      - .env.docker

  # swagger-editor:
  #   build:
  #     context: ./docker/swagger-editor/
  #   volumes:
  #     - ./openapi.yml:/usr/share/nginx/html/static/openapi.yml
  #   ports:
  #     - 8888:80

  # swagger-ui:
  #   image: swaggerapi/swagger-ui
  #   ports:
  #     - 3080:8080
  #   volumes:
  #     - ./openapi.yml:/app/openapi.yml
  #   environment:
  #     - SWAGGER_JSON=/app/openapi.yml
  #     - WITH_CREDENTIALS=true

volumes:
  middleware-nodemodules:
