version: "3.8"

services:
  db:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}

  cloudbeaver:
    image: dbeaver/cloudbeaver
    ports:
      - 8979:8978
    volumes:
      - cloudbeaver_data:/opt/cloudbeaver/workspace
    links:
      - db

  postgres-exporter:
    image: prometheuscommunity/postgres-exporter
    ports:
      - 9187:9187
    links:
      - db
    environment:
      DATA_SOURCE_URI: ${DB_HOST}:5432/${DB_NAME}?sslmode=disable
      DATA_SOURCE_USER: ${DB_USER}
      DATA_SOURCE_PASS: ${DB_PASS}

  api:
    build:
      dockerfile: ./docker/api/Dockerfile
      context: .
    ports:
      - 8080:8080
    volumes:
      - .:/usr/app
    links:
      - db
    env_file:
      - .env
      - .env.docker

  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./docker/prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    links:
      - api
      - postgres-exporter

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - grafana_storage:/var/lib/grafana
      - ./docker/grafana/provisioning/:/etc/grafana/provisioning/
    links:
      - prometheus
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: true

volumes:
  db_data:
  cloudbeaver_data:
  prometheus_data:
  grafana_storage:
