// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Employee struct {
	ID         int32
	Uid        pgtype.UUID
	PersonioID int32
	FirstName  string
	LastName   pgtype.Text
	Email      string
	PictureUrl pgtype.Text
	Position   string
	Birthday   pgtype.Text
	PartnerID  int32
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type EmployeesLanguage struct {
	ID         int32
	EmployeeID int32
	LanguageID int32
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type EmployeesView struct {
	ID             int32
	Uid            pgtype.UUID
	PersonioID     int32
	FirstName      string
	LastName       pgtype.Text
	Email          string
	PictureUrl     pgtype.Text
	Position       string
	Birthday       pgtype.Text
	PartnerID      int32
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	AsciiFirstName string
	AsciiLastName  string
	IsBirthday     bool
	IsTeamCaptain  interface{}
}

type Language struct {
	ID        int32
	Name      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Partner struct {
	ID          int32
	Name        string
	LogoUrl     string
	Description pgtype.Text
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type SlackInfo struct {
	ID         int32
	Name       string
	SlackID    string
	EmployeeID int32
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
	AvatarUrl  pgtype.Text
}

type TeamCaptain struct {
	ID         int32
	EmployeeID int32
	PartnerID  int32
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}
