// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type DeprecatedTeamCaptain struct {
	ID         int32
	EmployeeID int32
	PartnerID  int32
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type Employee struct {
	ID          int32
	Uid         pgtype.UUID
	PersonioID  int32
	FirstName   string
	LastName    pgtype.Text
	Email       string
	PictureUrl  pgtype.Text
	Position    string
	Birthday    pgtype.Text
	PartnerID   int32
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	SoftDeleted bool
}

type EmployeePin struct {
	EmployeeID int32
	PinID      int32
	CategoryID int32
	DeletedAt  pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type EmployeesLanguage struct {
	ID         int32
	EmployeeID int32
	LanguageID int32
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type EmployeesView struct {
	ID             int32
	Uid            pgtype.UUID
	PersonioID     int32
	FirstName      string
	LastName       pgtype.Text
	Email          string
	Position       string
	Birthday       pgtype.Text
	PartnerID      int32
	SoftDeleted    bool
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	AsciiFirstName string
	AsciiLastName  string
	IsBirthday     interface{}
	IsTeamCaptain  interface{}
	PictureUrl     pgtype.Text
}

type Language struct {
	ID        int32
	Name      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Partner struct {
	ID          int32
	Name        string
	LogoUrl     string
	Description pgtype.Text
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type Pin struct {
	ID             int32
	EventDate      pgtype.Date
	ImagePin       string
	PinTitle       string
	PinDescription string
	AutoAssigned   pgtype.Bool
	CategoryID     int32
	DeletedAt      pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type PinsCategory struct {
	ID        int32
	Name      string
	DeletedAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type SlackInfo struct {
	ID         int32
	Name       string
	SlackID    string
	EmployeeID int32
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
	AvatarUrl  pgtype.Text
}

type TeamCaptain struct {
	ID            int32
	EmployeeID    int32
	TeamCaptainID int32
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}
