// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: pins.sql

package repository

import (
	"context"
)

const createPinCategory = `-- name: CreatePinCategory :one
INSERT INTO pins_category (
    name,
    created_at,
    updated_at
) VALUES (
    $1,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
)
RETURNING id, name, created_at, updated_at
`

func (q *Queries) CreatePinCategory(ctx context.Context, name string) (PinsCategory, error) {
	row := q.db.QueryRow(ctx, createPinCategory, name)
	var i PinsCategory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
