global:
  scrape_interval: 10s

scrape_configs:
  - job_name: api
    metrics_path: /api/v1/metrics
    static_configs:
      - targets:
          - api:3000
  - job_name: postgres
    static_configs:
      - targets:
          - postgres-exporter:9187
