// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: languages.sql

package repository

import (
	"context"
)

const createLanguage = `-- name: CreateLanguage :one
INSERT INTO languages (
  name
) VALUES (
  $1
)
RETURNING id, name, created_at, updated_at
`

func (q *Queries) CreateLanguage(ctx context.Context, name string) (Language, error) {
	row := q.db.QueryRow(ctx, createLanguage, name)
	var i Language
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLanguage = `-- name: GetLanguage :one
SELECT id, name, created_at, updated_at FROM languages
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetLanguage(ctx context.Context, id int32) (Language, error) {
	row := q.db.QueryRow(ctx, getLanguage, id)
	var i Language
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listLanguages = `-- name: ListLanguages :many
SELECT id, name, created_at, updated_at FROM languages
ORDER BY name
`

func (q *Queries) ListLanguages(ctx context.Context) ([]Language, error) {
	rows, err := q.db.Query(ctx, listLanguages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Language
	for rows.Next() {
		var i Language
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
