// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: offices.sql

package repository

import (
	"context"
)

const createOffice = `-- name: CreateOffice :one
INSERT INTO offices (
  name
) VALUES (
  $1
)
RETURNING id, name, created_at, updated_at
`

func (q *Queries) CreateOffice(ctx context.Context, name string) (Office, error) {
	row := q.db.QueryRow(ctx, createOffice, name)
	var i Office
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOffice = `-- name: GetOffice :one
SELECT id, name, created_at, updated_at FROM offices
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetOffice(ctx context.Context, id int32) (Office, error) {
	row := q.db.QueryRow(ctx, getOffice, id)
	var i Office
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOffices = `-- name: ListOffices :many
SELECT id, name, created_at, updated_at FROM offices
ORDER BY name
`

func (q *Queries) ListOffices(ctx context.Context) ([]Office, error) {
	rows, err := q.db.Query(ctx, listOffices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Office
	for rows.Next() {
		var i Office
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
