version: "3.8"

services:
  db:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${API_DB_NAME}
      POSTGRES_USER: ${API_DB_USER}
      POSTGRES_PASSWORD: ${API_DB_PASS}

  cloudbeaver:
    image: dbeaver/cloudbeaver
    ports:
      - 8979:8978
    volumes:
      - cloudbeaver_data:/opt/cloudbeaver/workspace
      - ./docker/cloudbeaver/conf/initial-data-sources.conf:/opt/cloudbeaver/conf/initial-data-sources.conf
    depends_on:
      - db
    environment:
      CB_SERVER_NAME: CloudBeaver
      CB_SERVER_URL: http://cloudbeaver:8978
      CB_ADMIN_NAME: cbadmin
      CB_ADMIN_PASSWORD: admin

  api:
    build:
      dockerfile: ./Dockerfile.local
      context: .
    ports:
      - 8080:8080
    volumes:
      - .:/usr/app
    depends_on:
      - db
    env_file:
      - .env
      - .env.docker

volumes:
  db_data:
  cloudbeaver_data:
