services:
  db:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${API_DB_NAME}
      POSTGRES_USER: ${API_DB_USER}
      POSTGRES_PASSWORD: ${API_DB_PASS}

  api:
    build:
      dockerfile: ./Dockerfile.local
      context: .
    ports:
      - 8080:8080
    volumes:
      - .:/usr/app
    depends_on:
      - db
    env_file:
      - .env
      - .env.docker

volumes:
  db_data:
