name: Wake up servers

on:
  schedule:
    - cron: '*/5 6-20 * * *'

jobs:
  wake-up-servers:
    runs-on: ubuntu-latest

    steps:
      - name: Wake up production server
        run: curl https://api.app.rindus.de/

      - name: Wake up staging server
        run: curl https://api-prod-8x7s.onrender.com
