services:
  wiremock:
    image: wiremock/wiremock
    ports:
      - 8081:8080
    volumes:
      - "./mock/mappings/:/home/wiremock/mappings/"
      - "./mock/responses/:/home/wiremock/__files/"

  app:
    command: "npm run dev:mock -- --host"